name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
  PYGAME_HIDE_SUPPORT_PROMPT: "1"
  SDL_VIDEODRIVER: dummy
  # Avoid locale surprises that can break string tests
  LC_ALL: C.UTF-8
  LANG: C.UTF-8
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system deps (SDL)
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install pygame noise pytest

      - name: Quick repo doctor (headless & smoke)
        run: |
          python tools/repo_doctor.py --headless --smoke 1.0 || true

      - name: Run tests
        run: |
          pytest -q
