name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file tests/environment.yml --name base
    -       - name: Lint (syntax/undefined-names)
        run: |
          # Fail the build on syntax or undefined names *only* in our source/tests
          flake8 src tests --select=E9,F63,F7,F82

      - name: Lint (style; non-blocking)
        run: |
          # Run a broader style check but don't fail the build on style only
          flake8 src tests || true

    - name: Test with pytest
      run: |
        conda install pytest
        pytest
